# Site settings
title: Kevin VanderLugt
email: kevin.vanderlugt@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://kevinvanderlugt.github.io"
url: "http://kevinvanderlugt.github.io"

# Build settings
markdown: kramdown
permalink: /:title

sass:
    sass_dir: css/_sass
    style: :compressed
